import { MthColor } from '@mth/enums'

export const recordClassess = {
  btnGroup: {
    justifyContent: 'flex-end',
    display: 'flex',
    height: '100%',
    alignItems: 'end',
    flexDirection: 'row',
  },
  record: {
    justifyContent: 'center',
    display: 'flex',
    height: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    border: '1px solid #ccc',
    padding: 2,
    borderRadius: 3,
  },
  clearAllBtn: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 2,
    textTransform: 'none',
    background: MthColor.RED_GRADIENT,
    color: 'white',
    width: '140px',
  },
  filterBtn: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 2,
    marginLeft: 5,
    marginRight: 5,
    textTransform: 'none',
    background: MthColor.BUTTON_LINEAR_GRADIENT,
    color: 'white',
    width: '140px',
  },
  dropDownContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'start',
    mt: 3,
    marginLeft: '-13px',
    alignItems: 'left',
  },
  header: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'row',
    marginLeft: '24px',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateGroup: {
    display: 'flex',
    my: 1,
    gap: '6px',
    justifyContent: 'space-between',
    alignItems: 'end',
  },
}
