import { MthColor } from '@mth/enums'

export const useStyles = {
  modalCard: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 850,
    bgcolor: 'white',
    boxShadow: 24,
    padding: '16px 32px',
    borderRadius: 2,
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerRight: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '200px',
  },
  close: {
    background: 'black',
    borderRadius: 2,
    color: 'white',
    cursor: 'pointer',
  },
  content: {
    padding: '15px',
  },
  emailViewContent: {
    padding: '0 50px',
  },
  submitButton: {
    borderRadius: '8px',
    width: '90px',
    '&:hover': {
      backgroundColor: '#313131',
    },
  },
  formRow: {
    display: 'flex',
    alignItems: 'center',
    height: '39px',
    width: '80%',
  },
  formLabel: {
    position: 'relative',
    color: '#000000',
    paddingLeft: '12px',
  },
  formEllipLabel: {
    position: 'relative',
    color: '#000000',
    paddingLeft: '12px',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    maxWidth: '78%',
    overflow: 'hidden',
  },
  formText: {
    position: 'relative',
    color: '#000000',
    paddingLeft: '12px',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    maxWidth: '70%',
    overflow: 'hidden',
  },
  formValue: {
    padding: '0 30px',
    color: '#7b61ff',
    position: 'relative',
  },
  labelAfter: {
    width: 0,
    height: '23px',
    borderRight: '1px solid #000000',
    position: 'absolute',
    top: 0,
    right: 0,
  },
  modalEmailCard: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 441,
    bgcolor: '#EEF4F8',
    boxShadow: 24,
    p: 2,
    borderRadius: 2,
  },
  modalEmailViewCard: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 800,
    bgcolor: 'background.paper',
    boxShadow: 24,
    p: 2,
    borderRadius: 2,
  },
  emailRowHead: {
    display: 'flex',
    alignItems: 'center',
    mb: 3,
  },
  subject: {
    marginTop: '30px',
    minHeight: '50px',
    border: '1px solid #CCCCCC',
    boxSizing: 'border-box',
    borderRadius: '5px',
    padding: '12px 20px',
  },
  body: {
    border: '1px solid #CCCCCC',
    boxSizing: 'border-box',
    borderRadius: '5px',
    minHeight: '360px',
    padding: '30px',
    marginBottom: '50px',
  },
  emailRow: {
    display: 'flex',
    alignItems: 'center',
    mb: 2,
    cursor: 'pointer',
  },
  emailLabel: {
    width: '135px',
    display: 'flex',
    alignItems: 'center',
  },
  emailViewLabel: {
    width: 'auto',
    display: 'flex',
    alignItems: 'center',
  },
  ok: {
    borderRadius: 10,
    width: '9px',
    height: '19px',
    marginTop: 4,
  },
  selectIcon: {
    fill: '#F2F2F2',
    color: '#F2F2F2',
  },
  selectRoot: {
    color: '#F2F2F2',
  },
  add: {
    borderRadius: '8px',
    textTransform: 'none',
    height: 40,
    background: MthColor.BUTTON_LINEAR_GRADIENT,
    color: 'white',
    fontSize: 14,
    fontWeight: 500,
    padding: '15px',
  },
  customizeModalContainer: {
    position: 'absolute' as const,
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '50%',
    bgcolor: 'background.paper',
    boxShadow: 24,
    p: 2,
    paddingLeft: '18px',
    borderRadius: 2,
  },
  editContent: {
    marginTop: '10px',
    paddingBottom: '20px',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: 'calc(100% - 60px)',
    overflow: 'auto',
    overflowX: 'hidden',
    '&::-webkit-scrollbar': {
      width: '5px',
    },
    '&::-webkit-scrollbar-track': {
      background: '#ffffff',
    },

    '&::-webkit-scrollbar-thumb': {
      background: '#888',
    },

    '&::-webkit-scrollbar-thumb:hover': {
      background: '#555',
    },
  },
  btnGroup: {
    display: 'flex',
    justifyContent: 'space-around',
    marginTop: '60px',
    gap: '20px',
  },
  cancelBtn: {
    width: '200px',
    height: '48px',
    fontSize: '12px',
    background: '#E7E7E7',
    borderRadius: '50px',
  },
  saveBtn: {
    background: 'linear-gradient(90deg, #3E2783 0%, rgba(62, 39, 131, 0) 100%), #4145FF',
    color: 'white',
    width: '140px',
    height: '48px',
    marginRight: '40px',
    marginTop: '40px',
    '&:hover': {
      backgroundColor: '#4145FF',
    },
    borderRadius: '8px',
    fontSize: '12px',
  },
  modalSaveBtn: {
    width: '200px',
    height: '48px',
    background: '#000000',
    borderRadius: '50px',
    fontSize: '12px',
    color: 'white',
  },
}
