import { DropDownItem } from '@mth/components/DropDown/types'
import { CheckBoxListVM } from '@mth/components/MthCheckboxList/MthCheckboxList'
import { RadioGroupOption } from '@mth/components/MthRadioGroup/types'
import { QUESTION_TYPE, ReimbursementQuestionSlug } from '@mth/enums'
import { AdditionalQuestionAction, ReimbursementFormType } from '@mth/enums'
import { ReimbursementQuestion } from '@mth/models'

export const DEFAULT_IS_DIRECT_ORDER_TECHNOLOGY_QUESTIONS: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.STUDENT_ID,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.FORM_TYPE,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.TEXTBOX,
    priority: 2,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.TOTAL_AMOUNT,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 3,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.SIGNATURE_NAME,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_TECHNOLOGY_QUESTIONS: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.STUDENT_ID,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.FORM_TYPE,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 2,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.RECEIPTS,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 2,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.TOTAL_AMOUNT,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 3,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.SIGNATURE_NAME,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_IS_DIRECT_ORDER_SUPPLEMENTAL_LEARNING_QUESTIONS: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.STUDENT_ID,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.FORM_TYPE,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.TEXTBOX,
    priority: 2,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.TOTAL_AMOUNT,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 3,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.SIGNATURE_NAME,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_SUPPLEMENTAL_LEARNING_QUESTIONS: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.STUDENT_ID,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.FORM_TYPE,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 2,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.RECEIPTS,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 2,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.TOTAL_AMOUNT,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 3,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.SIGNATURE_NAME,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_IS_DIRECT_ORDER_CUSTOM_BUILT_QUESTIONS: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.STUDENT_ID,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.FORM_TYPE,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 2,
    question: 'Period',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.PERIOD,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.TEXTBOX,
    priority: 3,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.TOTAL_AMOUNT,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 4,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.SIGNATURE_NAME,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_CUSTOM_BUILT_QUESTIONS: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.STUDENT_ID,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.FORM_TYPE,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 2,
    question: 'Period',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.PERIOD,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 3,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.RECEIPTS,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 4,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.TOTAL_AMOUNT,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 5,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.SIGNATURE_NAME,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_THIRD_PARTY_PROVIDER_QUESTIONS: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.STUDENT_ID,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.FORM_TYPE,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 2,
    question: 'Period',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.PERIOD,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 3,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.RECEIPTS,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 4,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.TOTAL_AMOUNT,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 5,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.SIGNATURE_NAME,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_REQUIRED_SOFTWARE_QUESTIONS: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.STUDENT_ID,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.FORM_TYPE,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 2,
    question: 'Period',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.PERIOD,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 3,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.RECEIPTS,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 4,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.TOTAL_AMOUNT,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 5,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.SIGNATURE_NAME,
    default_question: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export enum REIMBURSEMENT_DEFAULT_QUESTION {
  NEW_DEVICE = 'New Device',
}

export const REIMBURSEMENT_DEFAULT_QUESTIONS: RadioGroupOption[] = [
  {
    option_id: 1,
    label: REIMBURSEMENT_DEFAULT_QUESTION.NEW_DEVICE,
    value: false,
  },
]

export const DEFAULT_NEW_DEVICE_QUESTION: ReimbursementQuestion[] = [
  {
    type: QUESTION_TYPE.MULTIPLECHOICES,
    default_question: true,
    required: true,
    display_for_admin: false,
    priority: 0,
    question: 'Is this for a NEW (not used or refurbished computer, laptop, Chromebook, or iPad/tablet?',
    options: '',
    Options: [
      {
        label: 'Yes',
        value: 1,
        action: AdditionalQuestionAction.ASK_ADDITIONAL_QUESTION,
      },
      {
        label: 'No',
        value: 2,
        action: AdditionalQuestionAction.CONTINUE_TO_NEXT,
      },
      {
        label: '',
        value: '',
        action: AdditionalQuestionAction.CONTINUE_TO_NEXT,
      },
    ],
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.NEW_DEVICE,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    sortable: true,
    SettingList: ['required'],
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    default_question: true,
    required: false,
    display_for_admin: false,
    priority: 0,
    question:
      'NOTE: Please only include the new computer, laptop, Chromebook, or iPad/tablet on this Request for Reimbursement form. Submit a separate form for additional Technology Allowance items.<br />The Amount Paid should exclude takes. Note- this amount might be more than you are requesting for reimbursement.',
    options: '',
    Options: [],
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.NEW_DEVICE_INFORMATION,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    sortable: false,
    SettingList: [],
    additional_question: 'reimbursement_new_device',
  },
  {
    type: QUESTION_TYPE.TEXTBOX,
    default_question: true,
    required: true,
    display_for_admin: false,
    priority: 0,
    question: 'Item Name',
    options: '',
    Options: [],
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.NEW_DEVICE_ITEM_NAME,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    sortable: false,
    SettingList: ['required'],
    additional_question: 'reimbursement_new_device',
  },
  {
    type: QUESTION_TYPE.TEXTBOX,
    default_question: true,
    required: true,
    display_for_admin: false,
    priority: 0,
    question: 'Item Serial Number',
    options: '',
    Options: [],
    SchoolYearId: 0,
    slug: ReimbursementQuestionSlug.NEW_DEVICE_ITEM_SERIAL_NUMBER,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    sortable: false,
    SettingList: ['required'],
    additional_question: 'reimbursement_new_device',
  },
]

export const QUESTION_SETTING_LIST: CheckBoxListVM[] = [
  { label: 'Required', value: 'required' },
  { label: 'Display for Admin Processing', value: 'display_for_admin' },
]

export const REIMBURSEMENT_QUESTION_TYPES: DropDownItem[] = [
  {
    value: QUESTION_TYPE.TEXTBOX,
    label: 'Text box',
  },
  {
    value: QUESTION_TYPE.TEXTFIELD,
    label: 'Text Field',
  },
  {
    value: QUESTION_TYPE.MULTIPLECHOICES,
    label: 'Multiple Choices',
  },
  {
    value: QUESTION_TYPE.CHECKBOX,
    label: 'Checkbox',
  },
  {
    value: QUESTION_TYPE.DROPDOWN,
    label: 'Dropdown',
  },
  {
    value: QUESTION_TYPE.AGREEMENT,
    label: 'Agreement',
  },
  {
    value: QUESTION_TYPE.INFORMATION,
    label: 'New Information',
  },
]

export const REIMBURSEMENT_ADDITIONAL_QUESTION_TYPES: DropDownItem[] = [
  {
    value: QUESTION_TYPE.TEXTFIELD,
    label: 'Text Field',
  },
  {
    value: QUESTION_TYPE.MULTIPLECHOICES,
    label: 'Multiple Choices',
  },
  {
    value: QUESTION_TYPE.CHECKBOX,
    label: 'Checkbox',
  },
  {
    value: QUESTION_TYPE.DROPDOWN,
    label: 'Dropdown',
  },
]

export const AdditionalQuestionActionList = [
  {
    label: 'Continue to next',
    value: AdditionalQuestionAction.CONTINUE_TO_NEXT.toString(),
  },
  {
    label: 'Ask additional question',
    value: AdditionalQuestionAction.ASK_ADDITIONAL_QUESTION.toString(),
  },
]
