import { QUESTION_TYPE } from '@mth/components/QuestionItem/QuestionItemProps'
import { ReimbursementFormType } from '@mth/enums'

export const DEFAULT_IS_DIRECT_ORDER_TECHNOLOGY_QUESTIONS = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_student_id',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_form_type',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.TEXTFIELD,
    priority: 2,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_total_amount_requested',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 3,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_signature_name',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_TECHNOLOGY_QUESTIONS = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_student_id',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_form_type',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 2,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_receipts',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 2,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_total_amount_requested',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 3,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_signature_name',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_IS_DIRECT_ORDER_SUPPLEMENTAL_LEARNING_QUESTIONS = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_student_id',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_form_type',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.TEXTFIELD,
    priority: 2,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_total_amount_requested',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 3,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_signature_name',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_SUPPLEMENTAL_LEARNING_QUESTIONS = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_student_id',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_form_type',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.SUPPLEMENTAL,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 2,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_receipts',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 2,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_total_amount_requested',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 3,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_signature_name',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_IS_DIRECT_ORDER_CUSTOM_BUILT_QUESTIONS = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_student_id',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_form_type',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 2,
    question: 'Period',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_period',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.TEXTFIELD,
    priority: 3,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_total_amount_requested',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 4,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_signature_name',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: true,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_CUSTOM_BUILT_QUESTIONS = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_student_id',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_form_type',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 2,
    question: 'Period',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_period',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 3,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_receipts',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 4,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_total_amount_requested',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.TECHNOLOGY,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 5,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_signature_name',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.CUSTOM_BUILT,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_THIRD_PARTY_PROVIDER_QUESTIONS = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_student_id',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_form_type',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 2,
    question: 'Period',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_period',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 3,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_receipts',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 4,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_total_amount_requested',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 5,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_signature_name',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.THIRD_PARTY_PROVIDER,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]

export const DEFAULT_REQUIRED_SOFTWARE_QUESTIONS = [
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 0,
    question: 'Student',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_student_id',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 1,
    question: 'Type',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_form_type',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.DROPDOWN,
    priority: 2,
    question: 'Period',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_period',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: false,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 3,
    question: 'Receipts',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_receipts',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.INFORMATION,
    priority: 4,
    question: 'Total Amount Requested',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_total_amount_requested',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
  {
    type: QUESTION_TYPE.SIGNATURE,
    priority: 5,
    question: 'Signature',
    options: '',
    required: true,
    SchoolYearId: 0,
    slug: 'reimbursement_signature_name',
    defaultQuestion: true,
    reimbursement_form_type: ReimbursementFormType.REQUIRED_SOFTWARE,
    is_direct_order: false,
    reimbursement_question_id: 0,
    sortable: true,
  },
]
