export enum CartEventType {
  ADD = 'add',
  ALLOW_REQUEST = 'allowRequest',
  DISALLOW_REQUEST = 'disallowRequest',
  ARCHIVE = 'archive',
  DELETE = 'delete',
  DUPLICATE = 'duplicate',
  EDIT = 'edit',
  RESTORE = 'restore',
  HIDE = 'hide',
  UN_HIDE = 'unHide',
  ADD_CART = 'addCart',
  REMOVE_CART = 'removeCart',
  CLICK = 'click',
  DETAILS = 'details',
  UNARCHIVE = 'unarchive',
}
