export enum UsernameFormat {
  FIRST_LAST = 'FIRST_LAST',
  LAST_FIRST_YEAR = 'LAST_FIRST_YEAR',
  LAST_FIRST = 'LAST_FIRST',
  LAST_FIRSTINITIAL = 'LAST_FIRSTINITIAL',
  LAST_FIRST_MTH = 'LAST_FIRST_MTH',
  LAST_FIRST_BIRTH_YEAR = 'LAST_FIRST_BIRTH_YEAR',
  FIRST_LAST_DOMAIN = 'FIRST_LAST_DOMAIN',
  STUDENT_EMAIL = 'STUDENT_EMAIL',
  PARENT_EMAIL = 'PARENT_EMAIL',
  GENERIC = 'GENERIC',
}
