import { GREEN_GRADIENT, RED_GRADIENT, YELLOW_GRADIENT, BUTTON_LINEAR_GRADIENT } from '../../../../utils/constants'

export const useStyles = {
  card: {
    paddingTop: '24px',
    marginBottom: '24px',
    paddingBottom: '12px',
  },
  select: {
    '& .MuiSvgIcon-root': {
      color: 'blue',
    },
  },
  pageHeader: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  pageHeaderContent: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'row',
    marginLeft: '24px',
    alignItems: 'center',
  },
  pageHeaderButtonGroup: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'flex-end',
    marginRight: '24px',
  },
  emailButton: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 2,
    textTransform: 'none',
    background: RED_GRADIENT,
    color: 'white',
    width: '157px',
    marginRight: 2,
    height: '33px',
    '&:hover': {
      background: '#D23C33',
      color: '#fff',
    },
  },
  withdrawalButton: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 2,
    textTransform: 'none',
    height: '33px',
    background: YELLOW_GRADIENT,
    color: 'white',
    width: '195px',
    marginRight: 2,
    '&:hover': {
      background: '#FFD626',
      color: '#fff',
    },
  },
  reinstateButton: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 2,
    textTransform: 'none',
    height: '33px',
    background: GREEN_GRADIENT,
    color: 'white',
    width: '195px',
    '&:hover': {
      background: '#33FF7C',
      color: 'fff',
    },
  },
  quickWithdrawalButton: {
    borderRadius: 2,
    textTransform: 'none',
    height: 29,
    color: 'white',
    width: '150px',
    background: BUTTON_LINEAR_GRADIENT,
    '&:hover': {
      background: '#D23C33',
      color: '#fff',
    },
  },
  container: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginY: 4,
    marginRight: '24px',
  },
  content: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'left',
  },
  buttonDiv: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'left',
    justifyContent: 'flex-end',
    marginLeft: '24px',
  },
}
