export const s3URL = 'https://infocenter-v2-dev.s3.us-west-2.amazonaws.com/'
export const SNOWPACK_PUBLIC_S3_URL = import.meta.env.SNOWPACK_PUBLIC_S3_URL
export const SNOWPACK_PUBLIC_S3_STUDENT_RECORD_FILES_DOWNLOAD = import.meta.env
  .SNOWPACK_PUBLIC_S3_STUDENT_RECORD_FILES_DOWNLOAD
export const SNOWPACK_PUBLIC_COUNTIES_TEMPLATE = import.meta.env.SNOWPACK_PUBLIC_COUNTIES_TEMPLATE
export const SNOWPACK_PUBLIC_SCHOOL_DISTRICT_TEMPLATE = import.meta.env.SNOWPACK_PUBLIC_SCHOOL_DISTRICT_TEMPLATE
export const SNOWPACK_PUBLIC_S3_UPLOAD = import.meta.env.SNOWPACK_PUBLIC_S3_UPLOAD
export const S3_UPLOAD_URL = import.meta.env.SNOWPACK_PUBLIC_S3_URL
