import { MthColor } from '@mth/enums'

export const addEventClassess = {
  cardBody: {
    paddingTop: '24px',
    marginBottom: '24px',
    paddingBottom: '12px',
  },
  pageTop: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pageTopRight: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginRight: '24px',
  },
  pageTitle: {
    textAlign: 'left',
    display: 'flex',
    flexDirection: 'row',
    marginLeft: '24px',
    alignItems: 'center',
  },
  cancelBtn: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 2,
    textTransform: 'none',
    background: MthColor.RED_GRADIENT,
    color: 'white',
    width: '92px',
    marginRight: 2,
    height: '33px',
    '&:hover': {
      background: '#D23C33',
      color: '#fff',
    },
  },
  saveBtn: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 2,
    textTransform: 'none',
    height: '33px',
    background: MthColor.BLUE_GRADIENT,
    color: 'white',
    width: '92px',
    marginRight: 2,
    '&:hover': {
      background: '#4145FF',
      color: '#fff',
    },
  },
  RSVPBtn: {
    fontSize: 11,
    fontWeight: 700,
    borderRadius: 2,
    textTransform: 'none',
    height: '33px',
    background: MthColor.BLUE_GRADIENT,
    color: 'white',
    width: '160px',
    marginRight: 2,
    '&:hover': {
      background: '#4145FF',
      color: '#fff',
    },
    marginY: 1,
  },
  subject: {
    marginTop: 2,
  },
  editor: {
    border: '1px solid #d1d1d1',
    borderRadius: 1,
    marginBottom: '24px',
    'div.DraftEditor-editorContainer': {
      minHeight: '300px',
      maxHeight: '400px',
      overflow: 'scroll',
      padding: 1,
      '.public-DraftStyleDefault-block': {
        margin: 0,
      },
    },
  },
  editorInvalid: {
    borderColor: MthColor.ERROR_RED,
  },
  arrowButton: {
    fontSize: '15px',
    stroke: 'black',
    strokeWidth: 2,
    marginTop: '3px',
    marginRight: '10px',
  },
  addRSVPButton: {
    color: '#000',
    borderRadius: 1,
    textTransform: 'none',
    height: 37,
    whiteSpace: 'nowrap',
    my: 1,
    width: '65%',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    marginBottom: 3,
  },
  card: {
    boxShadow: 'none',
    border: '1px solid #bfbdbd',
    borderRadius: '10px',
    marginTop: 2,
    padding: 2,
  },
}
