export const announcementSectionClasses = {
  cardBox: {
    display: 'flex',
    flexDirection: 'row',
    textAlign: 'left',
    marginTop: 2,
    justifyContent: 'space-between',
    marginX: 4,
  },
  mobileCardBox: {
    display: 'flex',
    flexDirection: 'row',
    textAlign: 'left',
    marginTop: 2,
    justifyContent: 'space-between',
  },
  mobileHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    width: '100%',
  },
  mobileIconBtn: { width: '44px', minWidth: '44px', height: '44px' },
  cardAll: {
    display: 'flex',
    flexDirection: 'row',
    textAlign: 'left',
    paddingX: '20px',
    marginTop: 2,
  },
  mobileItem: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: '30px',
    paddingTop: '30px',
    borderTop: '1px solid #ccc',
  },
  cardItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
  },
  button: {
    alignItems: 'center',
    textAlign: 'center',
    marginLeft: '',
    marginRight: 'auto',
  },
  readMore: {
    color: '#4145FF',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '14px',
    textDecoration: 'underline',
    paddingLeft: '5px',
  },
}
