
name: Continuous Integration

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node 17
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install
      run: npm install --legacy-peer-deps
    - name: Lint & Test
      run: npm run lint --check
    - name: Build
      run: yarn build-stag